[general]
font-mono = "CommitMono Nerd Font"
font-sans = "CommitMono Nerd Font"

[bar]
location = "bottom"
scale = 0.8999999761581421
dropdown-freeze-label = false
button-label-padding = 0.75
button-variant = "basic"
button-group-background = "bg-base"
button-group-module-gap = 0.0

[[bar.layout]]
monitor = "eDP-1"
left = ["dashboard", "hyprland-workspaces"]
center = []
right = [
  "systray",
  { modules = ["notifications", "custom-update-status", "media"], name = "updates" },
  { modules = [
    "volume",
    "network",
    "bluetooth",
    "battery",
  ], name = "system" },
  { modules = [
    "weather",
    "clock",
  ], name = "time" },
]

[[bar.layout]]
monitor = "*"
left = ["dashboard", "hyprland-workspaces"]
center = []
right = [
  "systray",
  "notifications",
  "volume",
  { modules = [
    "weather",
    "clock",
  ], name = "time" }
]

[osd]
position = "bottom-right"
margin = 0

[wallpaper]
engine-enabled = false

[modules.battery]
label-show = false
button-bg-color = "bg-base"

[modules.bluetooth]
label-show = false
button-bg-color = "bg-base"

[modules.clock]
dropdown-show-seconds = true
format = "%H:%M"
icon-show = false
border-color = "green"
icon-bg-color = "green"
label-color = "green"
button-bg-color = "bg-base"

[modules.hyprland-workspaces]
show-special = false
container-bg-color = "bg-base"

[modules.media]
icon-type = "default"
label-show = false
button-bg-color = "bg-base"

[modules.network]
label-show = false
button-bg-color = "bg-base"

[modules.notification]
popup-position = "bottom-right"
border-color = "blue"
icon-bg-color = "blue"
icon-color = "blue"
label-color = "blue"
label-show = false
button-bg-color = "bg-base"

[modules.systray]
button-bg-color = "bg-base"

[modules.volume]
label-show = false
button-bg-color = "bg-base"

[modules.weather]
icon-name = "ld-umbrella-off-symbolic"
label-show = false
location = "Arvada"
provider = "weather-api"
time-format = "24h"
units = "imperial"
weatherapi-key = "$WEATHER_KEY"
button-bg-color = "bg-base"

[[modules.custom]]
id = "update-status"
interval-ms = 3600000
command = """
current_rev=$(nixos-version --revision 2>/dev/null) || {
  exit $?
}
latest_rev=$(curl -fsSL --connect-timeout 5 https://nixos.org/channels/nixos-unstable/git-revision 2>/dev/null) || {
  exit $?
}

if [ "$current_rev" != "$latest_rev" ]; then
  echo '{"alt":"update-needed"}'
fi
"""
icon-map = { update-needed = "tb-alert-triangle-symbolic" }
label-show = false
hide-if-empty = true
button-bg-color = "bg-base"

[styling.palette]
bg = "#21252b"
blue = "#61afef"
elevated = "#393f4a"
fg = "#abb2bf"
fg-muted = "#5c6370"
green = "#98c379"
primary = "#56b6c2"
red = "#e86671"
surface = "#282c34"
yellow = "#e5c07b"
