$font = CommitMono Nerd Font Propo
$gray1 = rgba(40, 44, 52, 1.0)
$gray2 = rgba(49, 53, 63, 1.0)
$gray5 = rgba(171, 178, 191, 1.0)
$orange = rgba(209, 154, 102, 1.0)
$red = rgba(232, 102, 113, 1.0)
$green = rgba(152, 195, 121, 1.0)
$blue = rgba(97, 175, 239, 1.0)

background = $gray1
base = $gray1
text = $gray5
alternate_base = $gray2
accent = $blue
accent_secondary = $red
font_family = $font
font_family_monospace = $font
